[hooks]
#pre-commit = "cargo check && cargo clippy --all-targets --all -- -D warnings"
#pre-push = "cargo check && cargo clippy --all-targets --all -- -D warnings && cargo test -- --test-threads=1"
pre-push = "cargo build"
#post-commit = "echo yay"

[logging]
verbose = true
