[workspace]
members = ["qbase", "qrecovery", "qconnection", "qcongestion"]
default-members = ["qbase", "qrecovery", "qconnection", "qcongestion"]

[profile.bench]
debug = true

[profile.release]
debug = true
