[package]
name = "qrecovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-skiplist = "0.1"
crossbeam-epoch = "0.9"
slice-deque = "0.3"
bytes = "1"
